global_costmap:
  plugins:
    - {name: static_map_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer_3d, type: "costmap_2d::VoxelLayer"}
    - {name: obstacle_layer_2d, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 0.5

  inflation_layer:
    inflation_radius: 0.5
    cost_scaling_factor: 1.0
