global_costmap:
  robot_radius: 0.22
  footprint: [[0.05, -0.17], [-0.17, -0.17], [-0.28, 0], [-0.17, 0.17], [0.05, 0.17]]
  footprint_padding: 0.05
  plugins:
    - {name: static_map_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer_3d, type: "costmap_2d::VoxelLayer"}
    - {name: obstacle_layer_2d, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 0.5

  inflation_layer:
    inflation_radius: 0.3
    cost_scaling_factor: 10.0
