# Planner selection
base_global_planner: "global_planner/GlobalPlanner"
base_local_planner: "dwa_local_planner/DWAPlannerROS"

# Oscillation
oscillation_timeout: 15.0
oscillation_distance: 0.5

# Recovery behaviors
recovery_behavior_enabled: true
recovery_behaviors:
  - name: "conservative_reset"
    type: "clear_costmap_recovery/ClearCostmapRecovery"
  - name: "rotate_recovery"
    type: "rotate_recovery/RotateRecovery"
  - name: "aggressive_reset"
    type: "clear_costmap_recovery/ClearCostmapRecovery"
conservative_reset:
  reset_distance: 3.0
  layer_names: ["obstacle_layer_2d", "obstacle_layer_3d"]
rotate_recovery:
  frequency: 20.0
  sim_granularity: 0.017
aggressive_reset:
  reset_distance: 0.5
  layer_names: ["obstacle_layer_2d", "obstacle_layer_3d"]

# Global planner
planner_frequency: 0.5
planner_patience: 5.0
GlobalPlanner:
  allow_unknown: true
  default_tolerance: 0.0
  # debug
  visualize_potential: false
  publish_potential: false

# Local planner
controller_frequency: 25.0
controller_patience: 15.0
DWAPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.05
  # Non-holonomic robot -> no movement in y
  max_vel_y: 0
  min_vel_y: 0
  max_vel_theta: 0.4
  min_vel_theta: 0.1

  acc_lim_th: 1.0
  acc_lim_x: 1.0

  yaw_goal_tolerance: 0.15
  xy_goal_tolerance: 0.10
  latch_xy_goal_tolerance: true

  prune_plan: true

  # forward simulation
  sim_time: 1.7
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 4
  vth_samples: 20
  vy_samples: 0

  # scoring (defaults)
  path_distance_bias: 32
  goal_distance_bias: 24
  occdist_scale: 0.000 # NOTE(nickswalker,1-15-22): Non-zero values leading to robot getting stuck too often
  forward_point_distance: 0.325
  stop_time_buffer: 0.2

  # other
  oscillation_reset_dist: 0.05
  # debug
  publish_cost_grid: true
